### ISSUE TITLE
关于驱动使用的一些疑问

### ISSUE THREAD

**Issue by ZHH-start** [libdriver/ssd1306#25]
# 第一个问题
驱动抽象化极佳，但我有一些使用上的小细节不太明白，我没能成功驱动单色OLED屏幕，因此希望得到您的帮助。
![image](https://github.com/user-attachments/assets/e24ecdd7-e6ca-4f77-a6f7-34988b80fbb0)
我使用IIC驱动OLED，事先已经配置好了IIC驱动，并且做了部分移植。如图，这样的使用方法是对的吗？

# 第二个问题
![image](https://github.com/user-attachments/assets/7d83a626-6c51-42d2-8742-48eb04e78bdb)
![image](https://github.com/user-attachments/assets/eb89f89f-2685-4e9e-a053-1d5cc1773e9b)
![image](https://github.com/user-attachments/assets/0a8fa2a4-cf21-424b-af6f-8f5d87a25131)

我确定通讯正常进行，因为从机一直在应答。但是实际上屏幕*没有*显示。由于我没有使用SPI驱动。因此我没有对_interface部分的SPI驱动进行任何修改，同时由于不需要deinit，我也没有添加该部分驱动。请问这是正确的使用方法吗？

![image](https://github.com/user-attachments/assets/70a51d03-15ce-462e-aad5-bf4f1e0753dc)
![image](https://github.com/user-attachments/assets/0d7c7072-e8ec-49f7-baae-e13a33090a6e)

### Additional context

在此之前我成功使用其他驱动让OLED屏幕亮起，因此我确信这块屏幕是完全正常的。如果有任何需要我补充说明的部分，请告知我，对您的援助之手不胜感激！

**Comment by libdriver** [comment]
Thank you very much for using LibDriver. Based on the information you provided, we have found that the 'ssd1306_interface_iic-write (uint8_t addr, uint8_t reg, uint8_t * buf, uint16_tlen)' function does not seem to have a section for writing the register address, reg is the register address, and when writing data without specifying the register address, the chip will treat the first byte of the data as the register address, causing the entire driver to write incorrectly. You can refer to ssd1306/project/stm32f407/driver/src/stm32f407_driver_ssd1306_interface.c for more information

您好，非常感谢您使用LibDriver驱动。从您提供的信息分析，我们发现ssd1306_interface_iic_write(uint8_t addr, uint8_t reg, uint8_t *buf, uint16_t len)这个函数，似乎没有reg写入的部分，reg是寄存器地址，当执行写入操作时不指定寄存器地址直接写入数据时，芯片会将数据的第一个字节当做寄存器地址导致整个驱动写入错误，您可以参考ssd1306/project/stm32f407/driver/src/stm32f407_driver_ssd1306_interface.c实现您平台的IIC写入驱动。

**Comment by ZHH-start** [comment]
收到。抱歉我的回复迟到了三个月。这段时间发生了很多事情。您说得对，我也注意到了。我似乎使用了错误的函数。我将重试一遍。

**Comment by ZHH-start** [comment]
十分感谢！确实是这个问题。成功点亮了。
![1B810CF85D0D48901CB05AA8F9E0A443](https://github.com/user-attachments/assets/5f973978-654d-4470-bb4a-653aa2dc462d)
